plugins:
  desoc_badges_enabled:
    default: true
    client: true
  desoc_ipfs_gateway:
    default: 'https://w3s.link/ipfs'
    client: true
  desoc_app_url:
    default: 'https://soulbound-git-dev-de-sci-labs.vercel.app/'
    client: true
  desoc_factory_contract:
    client: true
    default: '0x5BB342Dc710dd6E4129b949B91934149dCD335Aa'
  desoc_contracts:
    client: true
    default: ''
    type: list
    placeholder:
      key: "desoc_contracts.key_placeholder"
      value: "desoc_contracts.value_placeholder"
  desoc_chain_id:
    client: true
    default: 5
  desoc_json_rpc:
    client: true
    default: ''
    placeholder:
      key: "desoc_json_rpc.key_placeholder"
      value: "desoc_json_rpc.value_placehoder"
  desoc_mainnet_json_rpc:
    client: true
    default: ''
    placeholder:
      key: "desoc_mainnet_json_rpc.key_placeholder"
      value: "desoc_mainnet_json_rpc.value_placehoder"
