plugins:
  desoc_badges_enabled:
    default: true
    client: true
  desoc_app_url:
    default: 'https://societies.desci.com/'
    client: true
  desoc_whitelist:
    client: true
    default: ''
    type: list
    placeholder:
      key: "desoc_whitelist.key_placeholder"
      value: "desoc_whitelist.value_placeholder"
  desoc_chain_id:
    client: true
    default: 5
  desoc_subgraph_url:
    client: true
    default: 'https://graph-goerli-dev.desci.com/subgraphs/name/desoc'
    placeholder:
      key: "desoc_subgraph_url.key_placeholder"
      value: "desoc_subgraph_url.value_placehoder"
  desoc_mainnet_json_rpc:
    client: true
    default: 'https://mainnet.infura.io/v3/1b91f66482d64c7e900913c7763227f2'
    placeholder:
      key: "desoc_mainnet_json_rpc.key_placeholder"
      value: "desoc_mainnet_json_rpc.value_placehoder"
